apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: sample-rs-multi-labels
spec:
  replicas: 3
  selector:
    matchLabels:
      app: sample-app-1
  template:
    metadata:
      labels:
        app: sample-app
        env: dev
    spec:
      containers:
        - name: nginx-container
          image: nginx:1.12
          ports:
            - containerPort: 80